bin/argparse-manpage

This shebang doesn't work on Debian, e.g. (on Fedora you have to
have python-unversioned-command installed).
Related: #17

Fix default shebang in argparse-manpage

---

README.md
bin/argparse-manpage
setup.py

This PR removes the manual `bin/argparse-manpage` entry_point-style script, and replaces it with an `entry_points` entry in `setup.py`. This should make it easier to build cross-platform builds of this package with, e.g, conda-build, and also means you don't have to worry about shebangs etc.

Provide argparse-manpage executable via entry_point

---

build_manpages/manpage.py
examples/copr/copr_cli/main.py
examples/copr/expected-output.1

Implements #5 
Renders epilog as `COMMENTS`.
Output from copr_example:

Add support for epilog using 'COMMENTS' section

---

build_manpages/manpage.py
examples/copr/copr_cli/main.py
examples/copr/expected-output.1
examples/raw-description/expected-output.1
examples/resalloc/expected/man/resalloc-maint.1
examples/resalloc/expected/man/resalloc.1
tests/test_basic.py

Hi again,
Here I introduce some opinion, that the manpage should separate the options by argument group rather than putting them all under the OPTIONS heading. For programs with lots of options it helps to organise them e.g. like https://wwood.github.io/CoverM/coverm-genome.html
Thoughts?

manpage: Split out options by argument group.

---

build_manpages/manpage.py
examples/argument_groups/bin/test
examples/argument_groups/expected/test.1
examples/argument_groups/setup.cfg
examples/argument_groups/setup.py
examples/copr/expected-output.1
examples/raw-description/expected-output.1
examples/resalloc/expected/man/resalloc-maint.1
examples/resalloc/expected/man/resalloc.1
tests/test_basic.py
tests/test_examples.py

The `add_argument_group()` can be used to add additional
title/description for sub-set of arguments.
Follow-up: #35, #37
Complements: 31f695fa4ea9f5dbdf86d49451d4e83c13c4f66f

Process _ArgumentGroups properly in the option list

---

tests/test_examples.py

Export one variable that reverts the default Fedora python installation
path behavior (install --root <root> and --prefix <pfx> works the old
way, no /usr/local enforced).

tests: pretend an RPM build

---

tests/test_examples.py

Testing with pretended RPM build environment does not test the actual behavior
of this library. This way, we assert the actual patch as intended by sysconfig.
This reverts commit 959f8173feed0ba36d90c994008515cfc0b86609.

Revert "tests: pretend an RPM build", check the actual path

---

MANIFEST.in
rpm/Makefile

The 'git archive' tarball doesn't provide the needed metadata for
'twine' uploads and without testing the 'sdist' tarball in CI the file
list got often de-synced (complicating the release process later).

rpm: use 'python setup.py sdist' tarball for CI

---

tests/test_examples.py

The in-tree builds are the default behavior for pip >= 21.3 now.
See also: https://github.com/pypa/pip/commit/040cc391baceaad0e8e294e7a3658f08fd12aee2

The in-tree-build flag from pip has been removed.

---

README.md
build_manpages/build_manpage.py
build_manpages/cli.py
build_manpages/manpage.py
examples/argument_groups/expected/test.1
examples/argument_groups/setup.cfg
examples/copr/expected-output.1
examples/copr/setup.cfg
examples/old_format/expected-output.1
examples/old_format_file_name/expected-output.1
examples/osc/expected-output.1
examples/osc/setup.cfg
examples/raw-description/expected-output.1
examples/resalloc/expected/man/resalloc-maint.1
examples/resalloc/expected/man/resalloc.1
tests/test_script.py

The new 'manual_section'/--manual-section allows us to specify a desired manual page version.
The new 'manual_title'/--manual--title option allows us to specify manual page title.
The 'version'/--version has a better documentation now, and is fixed so it has the effect.
The 'description'/--description now has the needed effect, and better documentation.
The 'long_description' is deprecated, unused and hidden.  It doesn't make sense to mixup project-description with the utility description. Utility description is directly in the Argparse object.
Added test-cases for all the variants.
Fixes: #15
Fixes: #62

Several new configuration/cmd-line options

---

setup.py

This was actually giving us a warning:
$ python setup.py build_py
...
file build_manpage.py (for module build_manpage) not found

setup: drop useless py_modules= statement

---

argparse_manpage/cli.py
argparse_manpage/manpage.py
build_manpages/build_manpages.py
tests/test_basic.py

The definition of the data= is blurry, and it's better to not use it from the outside, it could change.  Try to hide it from users (make it optional and private), and actually revert a change that the old Manpage() API.
Relates: #7

Manpage: don't require the data= option

---

argparse_manpage/manpage.py
build_manpages/build_manpage.py
tests/test_script.py

Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of this variable.
This patch was done while working on reproducible builds for openSUSE.

Allow to override build date with SOURCE_DATE_EPOCH

---

MANIFEST.in
README.md
argparse_manpage/cli.py
argparse_manpage/manpage.py
examples/argument_groups/expected/test.1
examples/copr/expected-output.1
examples/old_format/expected-output.1
examples/old_format_file_name/expected-output.1
examples/osc/expected-output.1
examples/raw-description/expected-output.1
examples/resalloc/expected/man/resalloc-maint.1
examples/resalloc/expected/man/resalloc.1
tests/extra.man
tests/test_script.py

I have tried to mimic as best I can the behaviour of help2man, without
changing the way that argparse-manpage works already.
The main effect of this is that the treatment of certain sections that are
individually rendered by argparse-manpage is slightly different from
help2man.
I have also renamed the non-standard “AUTHORS” section to the standard
“AUTHOR”.
I have not yet tried to document or add tests for the new functionality, in
case it’s desired to change it before merging.

Add --include command-line flag

---

README.md
argparse_manpage/compat.py
argparse_manpage/manpage.py
build_manpages/build_manpages.py
pyproject.toml
rpm/argparse-manpage.spec.tpl
setup.py
test-requirements.txt
tests/argparse_testlib.py
tests/test_examples.py
tests/test_script.py

This PR adds support for manpage specifications being supplied in the
tool.build_manpages section of pyproject.toml.
Also, it fixes author parsing to work with the information parsed from
pyproject.toml by setuptools, where only author_email is set, not
author (issue #77).

Allow argparse-manpages to be configured with pyproject.toml

---

README.md

That is, man pages installed with ‘manfile’ must be listed in ‘MANIFEST.in’.

README.md: note that pre-written manpages must be in manifest

---

README.md

`argparse-manpage` entry in Repology will be merged into `python:argparse-manpage`

Update repology badge

---

README.md

This PR fixes this error (that you get when you read the docs and implement the pyproject.toml example):
```console
running build_manpages
error: 'manpages' option is required
```

Fix the pyproject.toml manpages example

---

argparse_manpage/manpage.py

When `parser.format_usage()` output happens to contain any colons, the synopsis currently starts after the last of these colons. This splits just once to fix this.

Support colons in the parser's format_usage() output.

---

argparse_manpage/tooling.py

`/dev/stdout` isn't portable, it isn't available everywhere, e.g. on Haiku.

Use sys.stdout instead of /dev/stdout

---

argparse_manpage/manpage.py
build_manpages/build_manpage.py
examples/copr/copr_cli/main.py
tests/argparse_testlib.py
tests/test_script.py

Apparently pkg_resources could be removed on 2025-11-30.
https://setuptools.pypa.io/en/latest/pkg_resources.html
- datetime.datetime.utcfromtimestamp → datetime.datetime.fromtimestamp
- pkg_resources.parse_version → packaging.version.parse
- pkg_resources.require → importlib.metadata.version
```
tests/argparse_testlib.py:7
/argparse-manpage/tests/argparse_testlib.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
from pkg_resources import parse_version
tests/test_script.py:92
/argparse-manpage/tests/test_script.py:92: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and …
```

Fix deprecation warnings for datetime and setuptools

---

argparse_manpage/manpage.py

there was a bug, that made argparse-manpage fail with an exception when a subcommand had an empty `help` text (`action.help is None`). Fixed it.

fixed action.help is None bug within subcommand
